# Generated by Django 3.2.6 on 2021-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tittle', models.CharField(max_length=300)),
                ('desc', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='picture')),
            ],
        ),
    ]
